### ISSUE TITLE
package_data are not installed when installing pytzwhere with pip in a venv

### ISSUE THREAD

**Issue by seahawk1986** [pegler/pytzwhere#45]
Hello,
when installing tzwhere in a venv with pip using Python 3.6 (or 3.5) both json files 'tz_world.json' and            'tz_world_shortcuts.json' are missing:
``` shell
$ python3 -m venv test_pytzwhere
$ source test_pytzwhere/bin/activate
(test_pytzwhere) $ pip install tzwhere
(test_pytzwhere) $ tree test_pytzwhere/lib/python3.6/site-packages/tzwhere*
test_pytzwhere/lib/python3.6/site-packages/tzwhere
├── __init__.py
├── __pycache__
│   ├── __init__.cpython-36.pyc
│   └── tzwhere.cpython-36.pyc
└── tzwhere.py
test_pytzwhere/lib/python3.6/site-packages/tzwhere-3.0.1-py3.6.egg-info
├── PKG-INFO
├── SOURCES.txt
├── dependency_links.txt
├── installed-files.txt
├── requires.txt
└── top_level.txt
```

Removing the Line "include_package_data=True," from the setup.py (https://github.com/pegler/pytzwhere/blob/master/setup.py#L19) seems to fix the problem - is this needed by anything else?

**Comment by LowieHuyghe** [comment]
I'm having the same problem and would love to see it fixed!
Would it be possible to submit a pull request with your changes? Thanks in advance!

**Comment by seahawk1986** [comment]
I dug a little deeper into the setuptools documentation (https://setuptools.readthedocs.io/en/latest/setuptools.html?highlight=include_package_data#including-data-files) - the missing entries in the MANIFEST.in for those files seem to be the real cause for the missing files:
> if using the setuptools-specific include_package_data argument, files specified by package_data will not be automatically added to the manifest unless they are listed in the MANIFEST.in file.

So including those files to the MANIFEST.in seems to be the better solution (the file `tzwhere/tz_world.csv` mentioned in MANIFEST.in has been removed in https://github.com/pegler/pytzwhere/commit/df871d2dfaed96a8d537b0f57f2a6d00fd2bb024 )

#46 should fix the installation of those files.

**Comment by pegler** [comment]
Thanks @linwoodc3 and @seahawk1986 for the pull requests.  I ended up using @linwoodc3's since it added compression.  I just pushed version 3.0.2 to PyPI

**Comment by linwoodc3** [comment]
I have no idea what's going on anymore; I just tried it again, and the file is STILL missing.  I really don't know what we missed.  Double checking.....


![screen shot 2017-08-23 at 10 53 47 pm](https://user-images.githubusercontent.com/2884914/29647198-01016fc6-8856-11e7-90d3-9a630a9e4b09.png)

**Comment by pegler** [comment]
@linwoodc3 I just pushed v 3.0.3 with the fix
